name: Report Broken Companies / Hiring / Fake Job Posts
description: Report a company with broken hiring process or fake job posts
title: '[0001]: '
labels:
  - 0001 Broken Companies Hiring
assignees:
  - rrjanbiah
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report for the community benefit!
  - type: input
    id: company_name
    attributes:
      label: Company Name
      description: What is the company name?
      placeholder: Company Name
    validations:
      required: true
  - type: input
    id: company_url
    attributes:
      label: Company Website
      description: What is the company website/URL?
      placeholder: 'https://example.com/'
    validations:
      required: true
  - type: input
    id: job_url
    attributes:
      label: Related job posting
      description: What is the URL of the job description?
      placeholder: 'https://example.com/job-posting'
    validations:
      required: false
  - type: input
    id: job_role
    attributes:
      label: Applied/checked job role
      description: 'What is the job role? Or, at least share related nearest job role'
      placeholder: 'Engineering Manager, etc'
    validations:
      required: false
  - type: checkboxes
    id: broken_items
    attributes:
      label: What are broken?
      description: You may select more than one.
      options:
        - label: Whiteboard
        - label: Puzzles and leetcodes
        - label: Algorithms and irrelevance
        - label: Too many rounds
        - label: Free tasks / assignments
        - label: Weird NDA
        - label: Ethical issues
        - label: Ghosting
        - label: HR round
        - label: Technical round
        - label: Data mining
        - label: Racism
        - label: Sexism
        - label: Fake job post for backlinks, such as ```Ask HN Who is hiring```
        - label: Other
  - type: textarea
    id: experience
    attributes:
      label: What happened?
      description: Please explain your experience
      placeholder: null
      value: null
    validations:
      required: false
    render: yaml
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion for the community
      description: Please share your suggestion for the community members
      placeholder: null
      value: null
    validations:
      required: false
